#!/bin/env python3
from subprocess import check_output


def main():
    light = int(str(check_output('light')).split('.', maxsplit=1)[0].lstrip('b\''))

    print(f"{['', '', ''][light // 34]} {light}")


if __name__ == '__main__':
    main()
