#!/bin/env bash

mute=$(pactl get-source-mute @DEFAULT_SOURCE@)

if [[ ${mute#'Mute: '} == "yes" ]]; then
    echo  
else
    echo " $(pactl get-source-volume @DEFAULT_SOURCE@ | head -n 1 | awk '{print substr($5, 1, length($5)-1)}')"
fi


